railsapp/langylearny/config/routes.rb
Rails.application.routes.draw do
	
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	root 'pages#home'

  resources :users

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  resources :grammar_categories

  resources :vocabulary_categories

  resources :category_items

  resources :questions
  

end

railsapp/langylearny/app/models/category.rb
class Category < ActiveRecord::Base
	validates :name, presence: true
	validates :content, presence: true
	has_many :questions
	has_many :category_items
	
	def self.grammar_categ
		where(is_grammar_categ: true)
	end

	def self.vocabulary_categ
		where(is_grammar_categ: false)
	end
end

railsapp/langylearny/app/models/category_item.rb
class CategoryItem < ActiveRecord::Base
	belongs_to :category
	mount_uploader :image, ImageUploader
end

railsapp/langylearny/app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :category
end

railsapp/langylearny/app/models/question.rb
class Question < ActiveRecord::Base
	validates :content, presence: true
	belongs_to :category
end

railsapp/langylearny/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :first_name, presence: true
	validates :user_name, presence: true, length: { in: 5..20 }, uniqueness: true
end

railsapp/langylearny/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
  	@current_user ||= User.find_by(id: session[:user_id])
  end

  def require_user
  	redirect_to root_path unless current_user.present?
  end

end

railsapp/langylearny/app/controllers/category_items_controller.rb
class CategoryItemsController <ApplicationController

	before_action :require_user

	def show
		@category_item = CategoryItem.find(params[:id])
		render partial: "modal", layout: false
	end

end

railsapp/langylearny/app/controllers/grammar_categories_controller.rb
class GrammarCategoriesController <ApplicationController

	before_action :require_user

	def index
		@grammar_categories = Category.grammar_categ
	end

	def show
		@grammar_category = Category.grammar_categ.find(params[:id])

		session[:category_id] = @grammar_category.id
	end

end

railsapp/langylearny/app/controllers/images_controller.rb
class ImagesController <ApplicationController

end

railsapp/langylearny/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
	def home
	
	end

	def registration

	end
	
end

railsapp/langylearny/app/controllers/questions_controller.rb
class QuestionsController <ApplicationController
	
	before_action :require_user

	def index
		@questions = Question.where(category_id: session[:category_id])
	end

end

railsapp/langylearny/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		@user=User.new
	end

	def create

		@user=User.find_by(user_name: params[:session][:user_name])

		if @user && @user.authenticate(params[:session][:password])

			session[:user_id]=@user.id
			redirect_to root_url, notice: "You've been successfully logged in"

		else
			flash.now[:error]='Invalid username/password'
			render 'new'
		end
	end

	def destroy
		session.delete(:user_id)
		current_user = nil
		redirect_to root_url, notice: "You've been successfully logged out"
	end
end

railsapp/langylearny/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
	  @user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_url, notice: "You've been successfully registered in"
		else
			render 'new'
		end
	end

	private 
		def user_params
			params.require(:user).permit(:first_name, :last_name, :user_name, :password, :password_confirmation)
		end
end

railsapp/langylearny/app/controllers/vocabulary_categories_controller.rb
class VocabularyCategoriesController <ApplicationController

	before_action :require_user

	def index
		@vocabulary_categories=Category.vocabulary_categ
	end

	def show
		@vocabulary_category=Category.vocabulary_categ.find(params[:id])

		session[:category_id] = @vocabulary_category.id

		@category_items = @vocabulary_category.category_items.order(:id)
	end

end

railsapp/langylearny/app/helpers/application_helper.rb
module ApplicationHelper
end

railsapp/langylearny/app/views/categories/index.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
    <table class="table table-striped" id="grammar-categories-list">
      <thead>
        <tr>
          <th>Grammar Categories</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |c| %>
          <tr>
            <td>
            	<%= link_to c.name, category_url(c) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

railsapp/langylearny/app/views/categories/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 grammar-category-view">
    <h2><%= @category.name %></h2>
    <div class="grammar-content">
      <%= @category.content.html_safe %>
    <div>
  </div>
</div>

railsapp/langylearny/app/views/category_items/_modal.html.erb
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= @category_item.title %></h4>
      </div>
      <div class="modal-body">
          <%= @category_item.content %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>

railsapp/langylearny/app/views/grammar_categories/index.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
    <table class="table table-hover" id="grammar-categories-list">
      <thead>
        <tr>
          <th>Grammar Categories</th>
        </tr>
      </thead>
      <tbody>
        <% @grammar_categories.each do |c| %>
          <tr>
            <td class = "category-name">
            	<%= link_to c.name, grammar_category_url(c) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

railsapp/langylearny/app/views/grammar_categories/show.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1 grammar-category-view">
    <h2 class="title-on-page"><b><%= @grammar_category.name %></b></h2>
    <div class="grammar-content">
      <%= @grammar_category.content.html_safe %>
    <div>
   </div>
   <div id = "link-questions">
   	<%=link_to 'Want to take a test?', questions_path, class: "btn btn-primary btn-lg center-block bhome" %>
   	</div>
</div>

railsapp/langylearny/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LangyLearny</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" id="youshouldwork">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" >LangyLearny</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li class="active"><%=link_to 'Home', root_url %></li>
        <% if current_user.present? %>

          <li> <%=link_to 'Grammar Categories', grammar_categories_path %> </li>

          <li> <%= link_to 'Vocabulary Categories', vocabulary_categories_path %> </li>

          <li> <%=link_to 'Log out', logout_url, method: 'delete' %> </li>

        <% else %>

          <li> <%=link_to 'Registration', new_user_url %> </li>
          <li> <%=link_to 'Log in', login_url %> </li> 

        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid">
  <%=yield %>
</div>

</body>
</html>

railsapp/langylearny/app/views/pages/home.html.erb
<div>

<div id='welcome'>
<% if flash[:notice].present? %>
	<div class="alert alert-success" role="alert" >
		<%= flash[:notice] %>
	</div>
<% end %>

<h2>LangyLearny is a language game, as you may have figured! It was developed during the Learn IT, Girl! program by Mary and Dominika, so it shall be amazing!</h2>
</div>

</div>

<%=link_to "New here? Let's get started!", new_user_url, class: "btn btn-danger center-block bhome"%>

railsapp/langylearny/app/views/questions/index.html.erb
  
<div class = "row">
    <div class = "col-md-4 col-md-offset-4">
        <h2 class = "title-on-page">Questions</h3>
        <div id = "report"></div>
        <% @questions.each do |c| %>
        <div class = "individual-question">
            <p class = "content-text"><%= c.content %></p>
            <form>
              <input type="radio" name="question" value="1" id="q1a"><%= c.answer1 %><br/>
              <input type="radio" name="question" value="2" id="q1b"><%= c.answer2 %><br/>
              <input type="radio" name="question" value="3" id="q1c"><%= c.answer3 %><br/>
              <p class = "storage" ><%=c.right_answer%></p>
            </form>
        </div>
      <% end %>
    <button class = "btn btn-danger btn-lg center-block bhome submit_button"> SUBMIT! </button>
      </div>
</div>

railsapp/langylearny/app/views/users/new.html.erb
<div class="row">

	<div class="col-md-12">
		<h1>  Registration page </h1>

		<%= form_for @user, html: {class: 'form-horizontal', } do |f| %>
		<% if @user.errors.present? %>
			<div class="alert alert-danger" role="alert">
				<%= @user.errors.full_messages.join(', ') %>
			</div>
		<% end %>
		<div class="form-group">
    		<label class="col-md-2 col-sm-4 control-label">First name</label>
    		<div class="col-md-8 col-sm-6">
      			<%= f.text_field :first_name, class: 'form-control' %>
    		</div>
  		</div>
  		<div class="form-group">
    		<label class="col-md-2 col-sm-4 control-label">Last name</label>
    		<div class="col-md-8 col-sm-6">
      			<%= f.text_field :last_name, class: 'form-control' %>
    		</div>
  		</div>
  		<div class="form-group">
    		<label class="col-md-2 col-sm-4 control-label">User name</label>
    		<div class="col-md-8 col-sm-6">
      			<%= f.text_field :user_name, class: 'form-control' %>
    		</div>
  		</div>
  		<div class="form-group">
    		<label class="col-md-2 col-sm-4 control-label">Password</label>
    		<div class="col-md-8 col-sm-6">
      			<%= f.password_field :password, class: 'form-control' %>
    		</div>
  		</div>
  		<div class="form-group">
    		<label class="col-md-2 col-sm-4 control-label">Password Confirmation</label>
    		<div class="col-md-8 col-sm-6">
      			<%= f.password_field :password_confirmation, class: 'form-control' %>
    		</div>
  		</div>
  		<div class="col-md-8 col-md-offset-2">
			<%= f.submit 'Submit', class: 'btn btn-primary pull-right' %>	
		</div>
  		<% end %>
	</div>

</div>

railsapp/langylearny/app/views/vocabulary_categories/index.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
    <table class="table table-striped" id="grammar-categories-list">
      <thead>
        <tr>
          <th>Vocabulary Categories</th>
        </tr>
      </thead>
      <tbody>
        <% @vocabulary_categories.each do |c| %>
          <tr>
            <td>
            	<%= link_to c.name, vocabulary_category_url(c) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

railsapp/langylearny/app/views/vocabulary_categories/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2 grammar-category-view">
    <h2 class = "title-on-page"><%= @vocabulary_category.name %></h2>
    <div class="grammar-content">
      <%= @vocabulary_category.content.html_safe %>
    <div>
      <div class = "row">
        <% @category_items.each do |c| %>
              <div class = "col-sm-4 col-xs-6">
            	<%= image_tag c.image_url(:thumb), class: "modal_image", data: {id: c.id} %>
              </div>
             <% end %>
        </div>
      </div>
      </div>
  </div>
</div>
<div id = "link-questions">
    <%=link_to 'Want to take a test?', questions_path, class: "btn btn-primary btn-lg center-block bhome" %>
    </div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    
</div>